Feature/my wallet
dexe-network/investing-dashboard pull request #25
Opened 2022-06-13 13:27 UTC by saymon-develop

- [Add transactions list](https://github.com/dexe-network/investing-dashboard/commit/e9a4204e4bafb6f58958a68a917a4a78ed57040d)
- [Refactoring GradientBorder](https://github.com/dexe-network/investing-dashboard/commit/3b9cda5d974f305637eadcf9248304d776b6ac09)

2022-06-15 13:47 UTC, edward-arinin-web-dev requested changes

2022-06-17 08:43 UTC, saymon-develop commented on src/components/TransactionHistory/index.tsx
> +        style={{
Updated

2022-06-17 08:43 UTC, saymon-develop commented on src/components/TransactionHistory/index.tsx
> +        variants={{
Moved variants to motion/variants.ts

2022-06-17 08:45 UTC, saymon-develop commented on src/components/TransactionHistory/index.tsx
> +        transition={{ duration: 0.4 }}
Duration has been reduced to 0.2

2022-06-17 08:46 UTC, saymon-develop commented on src/pages/Wallet/index.tsx
>          animate={{ opacity: 1, y: 0 }}
- removed background from expanded list
- overlayed elements hided when list is open

2022-06-22 18:59 UTC, edward-arinin-web-dev approved these changes

2022-06-22 18:59 UTC, edward-arinin-web-dev commented on src/pages/Wallet/index.tsx
>          animate={{ opacity: 1, y: 0 }}
анимация топ 👍

2022-06-22 18:59 UTC, merged