Feature/transactions
dexe-network/investing-dashboard pull request #43
Opened 2022-08-11 15:37 UTC by saymon-develop

- [Added actual transaction types](https://github.com/dexe-network/investing-dashboard/commit/f6fea9534dda9822fda460c6d33187f8c8469e50)
- [Added interactions subgraph env](https://github.com/dexe-network/investing-dashboard/commit/8da8cccff2cbb1e7c7dbbc97f40352f3965e4f9c)
- [Improved useQueryPagination hook](https://github.com/dexe-network/investing-dashboard/commit/cf6e88863932e7f700f14f253e336c40929a4f95)
- [Fetch transactions history from subgraph](https://github.com/dexe-network/investing-dashboard/commit/0e22e4a707a84d8b0dc1702d2b5810a0fe3e0ce8)
- [Components and styles improves](https://github.com/dexe-network/investing-dashboard/commit/f35aa7e019a2c5601332bb6acd79d2f8aa1a44e5)

2022-08-12 16:55 UTC, edward-arinin-web-dev requested changes
Перед тем как запушить это в мастер, давай добавим текст (описал в комментарии).

2022-08-12 16:55 UTC, edward-arinin-web-dev commented on src/components/TransactionHistory/index.tsx
> +          {data.length &&
Если data.length === 0 -> то в UI (там где список) можно заметить символ: "0"

нужно сделать !!data.length

2022-08-12 16:55 UTC, edward-arinin-web-dev commented on src/components/cards/TransactionHistory/CardSwap.tsx
> +          View on bscscan
тут нужно будет заменить текст "View on bscscan" на более детальную инфу.
Например: "Swap DEXE for ETH". Если будут вопросы по этому - в пн обсудим.

2022-08-15 10:26 UTC, saymon-develop commented on src/components/TransactionHistory/index.tsx
> +          {data.length &&
done

2022-08-15 10:27 UTC, saymon-develop commented on src/components/cards/TransactionHistory/CardSwap.tsx
> +          View on bscscan
Добавил дополнительную инфу во обе карточки

2022-08-15 13:24 UTC, edward-arinin-web-dev requested changes
нужно пофиксить дату в 2 строки и делаем мердж

2022-08-15 13:24 UTC, edward-arinin-web-dev commented on src/components/cards/TransactionHistory/styled.tsx
> +    grid-template-columns: minmax(min-content, 1fr) 115px;
115px будет маловато. некоторые даты отображены в 2 строки из-за нехватки места

<img width="423" alt="Снимок экрана 2022-08-15 в 16 15 23" src="https://user-images.githubusercontent.com/59831011/184642311-0d373f29-ba50-4a6c-817c-b952d6129e31.png">

2022-08-15 13:24 UTC, edward-arinin-web-dev commented on src/components/cards/TransactionHistory/CardLiquidity.tsx
> +  const [, baseToken] = useERC20(poolInfo?.parameters.baseToken)
В будущем нужно будет сделать подгрузку данных о токене в контейнере на уровень выше.

что я имею ввиду.

Если у нас в списке 4 записи, например: DAI, DEXE, DAI, KTN.
1) формируем список из уникальных токенов [DAI, DEXE, KTN]
2) загружаем данные по этим токенам
3) передаём инфу о нужном токене в карточку

2022-08-15 13:45 UTC, edward-arinin-web-dev approved these changes

2022-08-15 14:06 UTC, merged

2022-08-15 14:15 UTC, saymon-develop commented on src/components/cards/TransactionHistory/CardLiquidity.tsx
> +  const [, baseToken] = useERC20(poolInfo?.parameters.baseToken)
Создал задачу для этого:
https://app.clickup.com/t/3bmnyup