feat: Redesign Header component
dexe-network/investing-dashboard pull request #489
Opened 2023-07-25 11:03 UTC by narekpetrosyan

## Description

Redesigned the **Header** component for both connected/not connected cases, added **TapBar** for mobile view, removed **Sidebar** from the screen. Also removed **children** prop from Header component.

## Checklist

- [ ] Requires dependency update?
- [x] Manually check the changes visually
- [x] Verify that the code compiles without errors or warnings
- [x] Looks good on large screens
- [x] Looks good on mobile
- [x] Confirm that no existing functionality has been broken by the changes
- [ ] Ensure that the pull request is small and consistent with one main task per pull request
- [x] Tag reviewers in the pull request

Closes [TASK-ID: #8692h5a5p](https://app.clickup.com/t/8692h5a5p)

2023-07-25 16:30 UTC, edward-arinin-web-dev approved these changes
1. fix broken font-family at comment section, placeholder: "add comment" https://localhost:3000/dao/0xbb807205a0dc94d3268b59be6dd2466c1ef0ba79/dao-proposals/off-chain/139/details
<img width="407" alt="feat_ Redesign Header component by narekpetrosyan · Pull Request #489 · dexe-network_investing-dashboard - Google Chrome 25 07 2023 19_29_19" src="https://github.com/dexe-network/investing-dashboard/assets/59831011/0da43458-f23a-461f-84ef-f3524265a272">

2. fix proposal tabs padding at https://localhost:3000/dao/0xbb807205a0dc94d3268b59be6dd2466c1ef0ba79/about
<img width="1492" alt="feat_ Redesign Header component by narekpetrosyan · Pull Request #489 · dexe-network_investing-dashboard - Google Chrome 25 07 2023 19_28_04" src="https://github.com/dexe-network/investing-dashboard/assets/59831011/dead5302-8fdf-41c4-8089-0c8b81edf25d">

2023-07-25 16:30 UTC, edward-arinin-web-dev commented on src/utils/index.ts
> -  return `${address.substring(0, chars + 2)}...${address.substring(42 - chars)}`
Do not change core functionalities

2023-07-25 16:38 UTC, edward-arinin-web-dev requested changes
fix issues described above before merge

2023-07-27 09:05 UTC, narekpetrosyan commented on src/utils/index.ts
> -  return `${address.substring(0, chars + 2)}...${address.substring(42 - chars)}`
Reversed.

2023-07-28 08:51 UTC, edward-arinin-web-dev approved these changes

2023-07-28 08:51 UTC, merged