Feature/dao settings inputs
dexe-network/investing-dashboard pull request #89
Opened 2022-10-03 15:28 UTC by lukachi

### Added

- AmountInputField
- ExternalDocumentField
- Form steps

2022-10-03 17:53 UTC, edward-arinin-web-dev requested changes

2022-10-03 17:53 UTC, edward-arinin-web-dev commented on src/fields/ExternalDocumentField/index.tsx
> +  useEffect(() => {
При повторной вставке ссылки в нижний инпут не обрабатывается Overlap

2022-10-03 17:53 UTC, edward-arinin-web-dev commented on src/fields/ExternalDocumentField/styled.tsx
> +export const TopInputField = styled(InputField)`
border-radius инпутов = 10px, на дизайне вижу что 16px должен быть

2022-10-03 17:53 UTC, edward-arinin-web-dev commented on src/fields/ExternalDocumentField/index.tsx
> +        label={label}
Галочка возле лейбла появляется когда вписываем имя документа, а ссылка еще не добавлена

2022-10-03 17:53 UTC, edward-arinin-web-dev commented on src/forms/CreateFundDaoForm/steps/IsDaoValidatorStep.tsx
> +                  label={`Address ${idx + 1}`}
Не сразу понял что сюда нужно адрес с блокчейна вставить, сразу https:// начал вставлять.
Предлагаю placehloder написать такой: `Adress 0x...`

2022-10-03 17:53 UTC, edward-arinin-web-dev commented on src/forms/CreateFundDaoForm/steps/IsDaoValidatorStep.tsx
> +                  overlapNodeLeft={
Чтобы разгрузить читаемость JSX предлагаю вынести контент overlapNodeLeft в функцию типа getFieldContentLeft()

2022-10-03 17:53 UTC, edward-arinin-web-dev commented on src/forms/CreateFundDaoForm/steps/IsDaoValidatorStep.tsx
> +                      onClick={() => {
также можно вынести в handleAddressDelete()

2022-10-04 09:05 UTC, lukachi commented on src/fields/ExternalDocumentField/styled.tsx
> +export const TopInputField = styled(InputField)`
✅

2022-10-04 09:20 UTC, lukachi commented on src/fields/ExternalDocumentField/index.tsx
> +  useEffect(() => {
✅

2022-10-04 09:22 UTC, lukachi commented on src/fields/ExternalDocumentField/index.tsx
> +        label={label}
✅

2022-10-04 09:25 UTC, lukachi commented on src/forms/CreateFundDaoForm/steps/IsDaoValidatorStep.tsx
> +                  label={`Address ${idx + 1}`}
✅

2022-10-04 10:23 UTC, lukachi commented on src/forms/CreateFundDaoForm/steps/IsDaoValidatorStep.tsx
> +                      onClick={() => {
✅

2022-10-04 10:53 UTC, lukachi commented on src/forms/CreateFundDaoForm/steps/IsDaoValidatorStep.tsx
> +                  overlapNodeLeft={
<img width="636" alt="Screenshot 2022-10-04 at 13 53 51" src="https://user-images.githubusercontent.com/39623143/193801560-742c25c7-5260-4195-a291-69e07d521446.png">

2022-10-04 16:06 UTC, edward-arinin-web-dev requested changes
в целом гуд! стало лучше.

заметил пару моментов:
- не всегда работает isValidUrl() в ExternalDocumentField
- https://app.clickup.com/t/30r208b?comment=1092332771

PS
я сделал небольшой комит и добавил placeholder "https://" для инпута адреса в ExternalDocumentField

2022-10-05 08:44 UTC, lukachi commented on src/fields/ExternalDocumentField/index.tsx
> +    if (url && isValidUrl(url)) {
Вернул проверку через new URL, оказывается, валидация через регулярку - не только не точное, то ещё и жутко тормозит

2022-10-05 10:07 UTC, merged